Document: qlshw
Title: Debian qlshw Manual
Author: <insert document author here>
Abstract: This manual describes what qlshw is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qlshw/qlshw.sgml.gz

Format: postscript
Files: /usr/share/doc/qlshw/qlshw.ps.gz

Format: text
Files: /usr/share/doc/qlshw/qlshw.text.gz

Format: HTML
Index: /usr/share/doc/qlshw/html/index.html
Files: /usr/share/doc/qlshw/html/*.html
